# Generated by Django 5.2.6 on 2025-09-28 22:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, '待機中'), (1, '処理中'), (2, '完了'), (3, '失敗')], default=0)),
                ('file', models.FileField(upload_to='input/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.PositiveSmallIntegerField(choices=[(0, 'image'), (1, 'pdf')])),
                ('total_pages', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='height_px', null=True, upload_to='input/img/', width_field='width_px')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, '待機中'), (1, '処理中'), (2, '完了'), (3, '失敗')], default=0)),
                ('page_number', models.PositiveSmallIntegerField(default=1)),
                ('width_px', models.PositiveIntegerField(blank=True, null=True)),
                ('height_px', models.PositiveIntegerField(blank=True, null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='app_ocr.document')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('direction', models.PositiveSmallIntegerField(choices=[(0, '横書き'), (1, '縦書き')])),
                ('rec_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('det_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='app_ocr.page')),
            ],
        ),
    ]
